In [23]:
import torch

In [24]:
x = torch.empty(5,3)  # 创建一个没有初始化的5*3矩阵
print(x) 

x = torch.rand(5,3) # 创建一个随机初始化的矩阵
print(x)

x = torch.zeros(5,3,dtype = torch.long) # 构造一个long型的零矩阵
print(x)

tensor([[6.3372e-39, 0.0000e+00, 4.4465e-36],
        [0.0000e+00, 1.2809e-38, 0.0000e+00],
        [2.8324e-21, 0.0000e+00, 2.8324e-21],
        [0.0000e+00, 1.7975e-39, 0.0000e+00],
        [6.4035e-39, 0.0000e+00, 6.4035e-39]])
tensor([[0.0424, 0.2290, 0.0360],
        [0.5054, 0.3997, 0.9274],
        [0.4399, 0.1947, 0.3678],
        [0.3824, 0.7032, 0.2789],
        [0.2868, 0.4046, 0.5321]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [25]:
## 根据数据构造张量
x = torch.tensor([5.5,3]) # 对照np.array([5,3])
print(x)

## 根据arange函数构建
torch.arange(5)## arange函数构建

## 根据已有的tensor建立新的tensor
x = x.new_ones(5,3,dtype=torch.double) 
print(x)
x = torch.randn_like(x,dtype=torch.float) # dtype属性被重载
print(x) # 除非用户提供新的值，否则这些方法将重用输入张量的属性，例如dtype

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4316,  0.9442, -0.7333],
        [-0.4011,  0.6446, -0.0746],
        [ 0.0423, -0.8395, -0.0127],
        [ 1.2147,  0.7956, -0.2860],
        [ 0.1807, -0.5309,  0.6978]])


In [26]:
## 计算形状（对照numpy.shape）
print(x.size()) # torch.size本质是tuple

x = torch.randn(4,4)
y = x.view(16) # 改变维数
z = x.view(-1,8) # -1表示从其他维度推断当前维数
print(x.size(), y.size(), z.size())

torch.Size([5, 3])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [27]:
x = torch.rand(5,3)
y = torch.rand(5,3)
print(x+y)

print(torch.add(x,y))

tensor([[0.9433, 0.8026, 1.5778],
        [1.1483, 0.8533, 1.8101],
        [0.7667, 0.9052, 1.0426],
        [0.6028, 1.0478, 0.7888],
        [0.9605, 0.8194, 0.9968]])
tensor([[0.9433, 0.8026, 1.5778],
        [1.1483, 0.8533, 1.8101],
        [0.7667, 0.9052, 1.0426],
        [0.6028, 1.0478, 0.7888],
        [0.9605, 0.8194, 0.9968]])


In [28]:
y.add_(x)
print(y)

tensor([[0.9433, 0.8026, 1.5778],
        [1.1483, 0.8533, 1.8101],
        [0.7667, 0.9052, 1.0426],
        [0.6028, 1.0478, 0.7888],
        [0.9605, 0.8194, 0.9968]])


In [29]:
a = torch.ones(5)
print(a) # 输出一个tensor

b = a.numpy() # 转化为numpy
print(b) # 输出一个数组

a.add_(1)
print(a)
print(b) # a与b均发生变化

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [30]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [31]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [32]:
y = x+2
print(y) # y是计算结果，所以有grad_fn属性
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [33]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [34]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [37]:

x = torch.ones(2,2, requires_grad = True)
y = x+2
z = y*y*3
out = z.mean()

out.backward() # out是标量，等价于out.backward(torch.tensor(1.))
print(x.grad) # 输出导数d(out)/dx 

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [38]:
x = torch.randn(3, requires_grad=True)

y = x * 2
y.data.norm()

tensor(2.8029)

In [41]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [42]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
